CREATE TABLE posts (
    id UUID PRIMARY KEY,
    author_id UUID NOT NULL,

    content VARCHAR(4096) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);