version: "3.8"

name: tipster-media
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  media:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: tipster_media
    ports:
      - "8082:8082"
    env_file:
      - ../.env
    environment:
      S3_ENDPOINT: minio:9000
      S3_PUBLIC_ENDPOINT: tipster.minio:9000
    extra_hosts:
      - "tipster.minio:host-gateway"
    depends_on:
      - minio
    networks:
      - default
      - tipster_apps

volumes:
  minio-data:

networks:
  tipster_apps:
    external: true
    name: tipster_apps