import { tokens } from "./tokens";

const light = {
  background: tokens.color.lightBg,
  background2: tokens.color.lightBg,
  text: tokens.color.gray11,
  // textSecondary: tokens.color.gray3,
  textSecondary: tokens.color.lightMuted,
  border: tokens.color.lightBorder,
  accent: tokens.color.accent,
  surface: tokens.color.lightInput,
  surfaceSecondary: tokens.color.gray7,
  placeholder: tokens.color.gray5,
  error: tokens.color.error,
  input: tokens.color.lightInput,
  muted: tokens.color.lightMuted,
  avatarBg: tokens.color.lightInput,
  inputBorder: tokens.color.lightBorder,
  inputPlaceholder: tokens.color.gray5,
  danger: tokens.color.danger,
  warning: tokens.color.warning,
  separator: tokens.color.lightBorder,
  textLight: tokens.color.gray7,
  tabActive: tokens.color.gray11,
  tabInactive: tokens.color.lightMuted,
};

const dark = {
  background: tokens.color.darkBg,
  background2: tokens.color.darkBg2,
  text: tokens.color.white,
  textSecondary: tokens.color.darkSecondary,
  border: tokens.color.darkBorder,
  accent: tokens.color.accent,
  surface: tokens.color.gray,
  surfaceSecondary: tokens.color.gray13,
  placeholder: tokens.color.darkPlaceholder,
  error: tokens.color.error,
  input: tokens.color.darkInput,
  muted: tokens.color.muted,
  avatarBg: tokens.color.darkSurface2,
  inputBorder: tokens.color.darkBorder2,
  inputPlaceholder: tokens.color.darkPlaceholder2,
  danger: tokens.color.danger,
  warning: tokens.color.warning,
  separator: tokens.color.separator,
  textLight: tokens.color.lightText,
  tabActive: tokens.color.darkBg,
  tabInactive: tokens.color.muted,
};

export const themes = {
  dark,
  light,
};
