openapi: 3.0.0
info:
  title: Tipster Authentication API
  version: 1.0.0
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tokens"
components:
  schemas:
    Tokens:
      type: object
      properties:
        access-token:
          type: string
        refresh-token:
          type: string
      required:
        - access-token
        - refresh-token
